### ISSUE TITLE
Add hacktoberfest birth year in description

### ISSUE THREAD

**Issue by aniket328** [aniket328/hacktober_website#11]
check the link for reference:
https://hacktoberfest.digitalocean.com

**Comment by BeAmazedVariable** [comment]
Hi would you mind to talk about more about this issue and how I can contribute to this ?

**Comment by aniket328** [comment]
No, need for an assignment, you can simply contribute, this repo is for general purpose hacktober participation pull requests.

**Comment by aniket328** [comment]
You can add more imformation and history about hacktober.

**Comment by aniket328** [comment]
> Can I do that instead? Really wish to contribute.
yes you can
